title: Sanjay Venkatesan
logo: /assets/img/head.jpeg
description: Sanjay Venkatesan is a Enthusiastic final-year student skilled in web penetration testing and cybersecurity, recognized by industry giants for uncovering vulnerabilities and fortifying web application security. And Keen on Learning new things.
show_downloads: true
theme: jekyll-theme-minimal
