title: Sanjay Venkatesan
logo: /assets/img/head.jpeg
description: Sanjay Venkatesan is an enthusiastic final-year student skilled in web penetration testing and cybersecurity, recognized by industry giants for uncovering vulnerabilities and fortifying web application security. Keen on learning new things.
#show_downloads: true
email: sanjaiv80@gmail.com
theme: jekyll-theme-minimal

email: sanjaiv80@gmail.com
social:
  linkedin: "https://www.linkedin.com/in/sanjay-venkatesan-5a478220b/"
  medium: "https://sanju1.medium.com/"
